display_name = "Osaka Jade"
theme_name = "osaka-jade"
accent = "#70a8c4"
foreground = "#C1C497"
background = "#111c18"
cursor = "#D7C995"
selection_foreground = "CellForeground"
selection_background = "#23372B"
color0 = "#23372B"
color1 = "#FF5345"
color2 = "#549e6a"
color3 = "#459451"
color4 = "#509475"
color5 = "#D2689C"
color6 = "#2DD5B7"
color7 = "#F6F5DD"
color8 = "#53685B"
color9 = "#db9f9c"
color10 = "#63b07a"
color11 = "#E5C736"
color12 = "#ACD4CF"
color13 = "#75bbb3"
color14 = "#8CD3CB"
color15 = "#9eebb3"

starship_palette_name = "osaka_jade"
rosewater = "#c8c8c8"
pink = "#c470a8"
mauve = "#a870c4"
red = "#c47070"
maroon = "#a85050"
peach = "#c49070"
yellow = "#c4b070"
green = "#6ea878"
teal = "#70c4a8"
sky = "#70a8c4"
sapphire = "#70a8c4"
blue = "#70a8c4"
lavender = "#a870c4"
text = "#c8c8c8"
subtext1 = "#989898"
subtext0 = "#707070"
overlay2 = "#585858"
overlay1 = "#404040"
overlay0 = "#303030"
surface2 = "#283430"
surface1 = "#1e2a28"
surface0 = "#182220"
base = "#182220"
mantle = "#141a18"
crust = "#101614"

nvim_content = '''return {
  {
    "ribru17/bamboo.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("bamboo").setup({})
      require("bamboo").load()
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "bamboo",
    },
  },
}
'''

btop_main_bg = "#111c18"
btop_main_fg = "#F7E8B2"
btop_title = "#D6D5BC"
btop_hi_fg = "#E67D64"
btop_selected_bg = "#364538"
btop_selected_fg = "#DEB266"
btop_inactive_fg = "#32473B"
btop_graph_text = "#E6D8BA"
btop_proc_misc = "#E6D8BA"
btop_cpu_box = "#81B8A8"
btop_mem_box = "#81B8A8"
btop_net_box = "#81B8A8"
btop_proc_box = "#81B8A8"
btop_div_line = "#81B8A8"
btop_temp_start = "#BFD99A"
btop_temp_mid = "#E1B55E"
btop_temp_end = "#DBB05C"
btop_cpu_start = "#5F8C86"
btop_cpu_mid = "#629C89"
btop_cpu_end = "#76AD98"
btop_free_start = "#5F8C86"
btop_free_mid = "#629C89"
btop_free_end = "#76AD98"
btop_cached_start = "#5F8C86"
btop_cached_mid = "#629C89"
btop_cached_end = "#76AD98"
btop_available_start = "#5F8C86"
btop_available_mid = "#629C89"
btop_available_end = "#76AD98"
btop_used_start = "#5F8C86"
btop_used_mid = "#629C89"
btop_used_end = "#76AD98"
btop_download_start = "#75BBB3"
btop_download_mid = "#61949A"
btop_download_end = "#215866"
btop_upload_start = "#215866"
btop_upload_mid = "#91C080"
btop_upload_end = "#549E6A"
btop_process_start = "#72CFA3"
btop_process_mid = "#D0D494"
btop_process_end = "#DB9F9C"

zellij_bg = "#111c18"
zellij_fg = "#C1C497"
zellij_black = "#23372B"
zellij_red = "#FF5345"
zellij_green = "#549e6a"
zellij_yellow = "#459451"
zellij_blue = "#509475"
zellij_magenta = "#D2689C"
zellij_cyan = "#2DD5B7"
zellij_white = "#F6F5DD"
zellij_orange = "#E5C736"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "'#111c18'"
alacritty_colors_primary_foreground = "'#C1C497'"
alacritty_colors_primary_dim_foreground = "'#8087a2'"
alacritty_colors_cursor_text = "'#000000'"
alacritty_colors_cursor_cursor = "'#D7C995'"
alacritty_colors_vi_mode_cursor_text = "'#000000'"
alacritty_colors_vi_mode_cursor_cursor = "'#D7C995'"
alacritty_colors_selection_text = "'CellForeground'"
alacritty_colors_selection_background = "'#23372B'"
alacritty_colors_normal_black = "'#23372B'"
alacritty_colors_normal_red = "'#FF5345'"
alacritty_colors_normal_green = "'#549e6a'"
alacritty_colors_normal_yellow = "'#459451'"
alacritty_colors_normal_blue = "'#509475'"
alacritty_colors_normal_magenta = "'#D2689C'"
alacritty_colors_normal_cyan = "'#2DD5B7'"
alacritty_colors_normal_white = "'#F6F5DD'"
alacritty_colors_bright_black = "'#53685B'"
alacritty_colors_bright_red = "'#db9f9c'"
alacritty_colors_bright_green = "'#63b07a'"
alacritty_colors_bright_yellow = "'#E5C736'"
alacritty_colors_bright_blue = "'#ACD4CF'"
alacritty_colors_bright_magenta = "'#75bbb3'"
alacritty_colors_bright_cyan = "'#8CD3CB'"
alacritty_colors_bright_white = "'#9eebb3'"
alacritty_font_size = "12.0"
