display_name = "Tokyo Night"
theme_name = "tokyo-night"
accent = "#7aa2f7"
foreground = "#a9b1d6"
background = "#1a1b26"
cursor = "#c0caf5"
selection_foreground = "#1a1b26"
selection_background = "#7aa2f7"
color0 = "#32344a"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#7aa2f7"
color5 = "#ad8ee6"
color6 = "#449dab"
color7 = "#787c99"
color8 = "#444b6a"
color9 = "#ff7a93"
color10 = "#b9f27c"
color11 = "#ff9e64"
color12 = "#7da6ff"
color13 = "#bb9af7"
color14 = "#0db9d7"
color15 = "#acb0d0"

starship_palette_name = "tokyo_night"
rosewater = "#c0caf5"
pink = "#bb9af7"
mauve = "#bb9af7"
red = "#f7768e"
maroon = "#db4b4b"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#73daca"
sky = "#7dcfff"
sapphire = "#7aa2f7"
blue = "#7aa2f7"
lavender = "#bb9af7"
text = "#a9b1d6"
subtext1 = "#9aa5ce"
subtext0 = "#565f89"
overlay2 = "#414868"
overlay1 = "#2f3549"
overlay0 = "#24283b"
surface2 = "#1f2335"
surface1 = "#1a1b26"
surface0 = "#13161c"
base = "#1a1b26"
mantle = "#16161e"
crust = "#13131a"

nvim_content = '''return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "tokyonight",
		},
	},
}
'''

btop_main_bg = "#1a1b26"
btop_main_fg = "#cfc9c2"
btop_title = "#cfc9c2"
btop_hi_fg = "#7dcfff"
btop_selected_bg = "#414868"
btop_selected_fg = "#cfc9c2"
btop_inactive_fg = "#565f89"
btop_proc_misc = "#7dcfff"
btop_cpu_box = "#565f89"
btop_mem_box = "#565f89"
btop_net_box = "#565f89"
btop_proc_box = "#565f89"
btop_div_line = "#565f89"
btop_temp_start = "#9ece6a"
btop_temp_mid = "#e0af68"
btop_temp_end = "#f7768e"
btop_cpu_start = "#9ece6a"
btop_cpu_mid = "#e0af68"
btop_cpu_end = "#f7768e"
btop_free_start = "#9ece6a"
btop_free_mid = "#e0af68"
btop_free_end = "#f7768e"
btop_cached_start = "#9ece6a"
btop_cached_mid = "#e0af68"
btop_cached_end = "#f7768e"
btop_available_start = "#9ece6a"
btop_available_mid = "#e0af68"
btop_available_end = "#f7768e"
btop_used_start = "#9ece6a"
btop_used_mid = "#e0af68"
btop_used_end = "#f7768e"
btop_download_start = "#9ece6a"
btop_download_mid = "#e0af68"
btop_download_end = "#f7768e"
btop_upload_start = "#9ece6a"
btop_upload_mid = "#e0af68"
btop_upload_end = "#f7768e"

zellij_bg = "#1a1b26"
zellij_fg = "#a9b1d6"
zellij_black = "#383e5a"
zellij_red = "#f93357"
zellij_green = "#9ece6a"
zellij_yellow = "#e0af68"
zellij_blue = "#7aa2f7"
zellij_magenta = "#bb9af7"
zellij_cyan = "#2ac3de"
zellij_white = "#c0caf5"
zellij_orange = "#ff9e64"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "'#1a1b26'"
alacritty_colors_primary_foreground = "'#a9b1d6'"
alacritty_colors_selection_background = "'#7aa2f7'"
alacritty_colors_normal_black = "'#32344a'"
alacritty_colors_normal_red = "'#f7768e'"
alacritty_colors_normal_green = "'#9ece6a'"
alacritty_colors_normal_yellow = "'#e0af68'"
alacritty_colors_normal_blue = "'#7aa2f7'"
alacritty_colors_normal_magenta = "'#ad8ee6'"
alacritty_colors_normal_cyan = "'#449dab'"
alacritty_colors_normal_white = "'#787c99'"
alacritty_colors_bright_black = "'#444b6a'"
alacritty_colors_bright_red = "'#ff7a93'"
alacritty_colors_bright_green = "'#b9f27c'"
alacritty_colors_bright_yellow = "'#ff9e64'"
alacritty_colors_bright_blue = "'#7da6ff'"
alacritty_colors_bright_magenta = "'#bb9af7'"
alacritty_colors_bright_cyan = "'#0db9d7'"
alacritty_colors_bright_white = "'#acb0d0'"
