format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true

palette = "tokyo_night"

[palettes.tokyo_night]
rosewater = "#c0caf5"
pink = "#bb9af7"
mauve = "#bb9af7"
lavender = "#bb9af7"
red = "#f7768e"
maroon = "#db4b4b"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#73daca"
sky = "#7dcfff"
sapphire = "#7aa2f7"
blue = "#7aa2f7"
text = "#a9b1d6"
subtext1 = "#9aa5ce"
subtext0 = "#565f89"
overlay2 = "#414868"
overlay1 = "#2f3549"
overlay0 = "#24283b"
surface2 = "#1f2335"
surface1 = "#1a1b26"
surface0 = "#13161c"
base = "#1a1b26"
mantle = "#16161e"
crust = "#13131a"
[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[package]
symbol = ' '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
