display_name = "Gruvbox"
theme_name = "gruvbox"
accent = "#83a598"
foreground = "#d4be98"
background = "#282828"
cursor = "#ebdbb2"
selection_foreground = "#282828"
selection_background = "#504945"
color0 = "#3c3836"
color1 = "#ea6962"
color2 = "#a9b665"
color3 = "#d8a657"
color4 = "#7daea3"
color5 = "#d3869b"
color6 = "#89b482"
color7 = "#d4be98"
color8 = "#3c3836"
color9 = "#ea6962"
color10 = "#a9b665"
color11 = "#d8a657"
color12 = "#7daea3"
color13 = "#d3869b"
color14 = "#89b482"
color15 = "#d4be98"

starship_palette_name = "gruvbox"
rosewater = "#ebdbb2"
pink = "#d3869b"
mauve = "#d3869b"
red = "#fb4934"
maroon = "#cc241d"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
sky = "#83a598"
sapphire = "#83a598"
blue = "#83a598"
lavender = "#b16286"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#665c54"
surface2 = "#504945"
surface1 = "#3c3836"
surface0 = "#282828"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"

nvim_content = '''return {
	{ "ellisonleao/gruvbox.nvim" },
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "gruvbox",
		},
	},
}
'''

btop_main_bg = "#282828"
btop_main_fg = "#a89984"
btop_title = "#ebdbb2"
btop_hi_fg = "#d79921"
btop_selected_bg = "#282828"
btop_selected_fg = "#fabd2f"
btop_inactive_fg = "#282828"
btop_graph_text = "#585858"
btop_proc_misc = "#98971a"
btop_cpu_box = "#a89984"
btop_mem_box = "#a89984"
btop_net_box = "#a89984"
btop_proc_box = "#a89984"
btop_div_line = "#a89984"
btop_temp_start = "#458588"
btop_temp_mid = "#d3869b"
btop_temp_end = "#fb4394"
btop_cpu_start = "#b8bb26"
btop_cpu_mid = "#d79921"
btop_cpu_end = "#fb4934"
btop_free_start = "#4e5900"
btop_free_mid = ""
btop_free_end = "#98971a"
btop_cached_start = "#458588"
btop_cached_mid = ""
btop_cached_end = "#83a598"
btop_available_start = "#d79921"
btop_available_mid = ""
btop_available_end = "#fabd2f"
btop_used_start = "#cc241d"
btop_used_mid = ""
btop_used_end = "#fb4934"
btop_download_start = "#3d4070"
btop_download_mid = "#6c71c4"
btop_download_end = "#a3a8f7"
btop_upload_start = "#701c45"
btop_upload_mid = "#b16286"
btop_upload_end = "#d3869b"

zellij_bg = "#282828"
zellij_fg = "#d5c4a1"
zellij_black = "#3c3836"
zellij_red = "#cc241d"
zellij_green = "#98971a"
zellij_yellow = "#d79921"
zellij_blue = "#3c8588"
zellij_magenta = "#b16286"
zellij_cyan = "#689d6a"
zellij_white = "#fbf1c7"
zellij_orange = "#d65d0e"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "\"0x282828\""
alacritty_colors_primary_foreground = "\"0xd4be98\""
alacritty_colors_selection_background = "\"#504945\""
alacritty_colors_normal_black = "\"0x3c3836\""
alacritty_colors_normal_red = "\"0xea6962\""
alacritty_colors_normal_green = "\"0xa9b665\""
alacritty_colors_normal_yellow = "\"0xd8a657\""
alacritty_colors_normal_blue = "\"0x7daea3\""
alacritty_colors_normal_magenta = "\"0xd3869b\""
alacritty_colors_normal_cyan = "\"0x89b482\""
alacritty_colors_normal_white = "\"0xd4be98\""
alacritty_colors_bright_black = "\"0x3c3836\""
alacritty_colors_bright_red = "\"0xea6962\""
alacritty_colors_bright_green = "\"0xa9b665\""
alacritty_colors_bright_yellow = "\"0xd8a657\""
alacritty_colors_bright_blue = "\"0x7daea3\""
alacritty_colors_bright_magenta = "\"0xd3869b\""
alacritty_colors_bright_cyan = "\"0x89b482\""
alacritty_colors_bright_white = "\"0xd4be98\""
