display_name = "Catppuccin"
theme_name = "catppuccin"
accent = "#89b4fa"
foreground = "#cad3f5"
background = "#24273a"
cursor = "#f4dbd6"
selection_foreground = "#24273a"
selection_background = "#f4dbd6"
color0 = "#494d64"
color1 = "#ed8796"
color2 = "#a6da95"
color3 = "#eed49f"
color4 = "#8aadf4"
color5 = "#f5bde6"
color6 = "#8bd5ca"
color7 = "#b8c0e0"
color8 = "#5b6078"
color9 = "#ed8796"
color10 = "#a6da95"
color11 = "#eed49f"
color12 = "#8aadf4"
color13 = "#f5bde6"
color14 = "#8bd5ca"
color15 = "#a5adcb"

starship_palette_name = "catppuccin_mocha"
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

nvim_content = '''return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin",
		},
	},
}
'''

btop_main_bg = "#1e1e2e"
btop_main_fg = "#cdd6f4"
btop_title = "#cdd6f4"
btop_hi_fg = "#89b4fa"
btop_selected_bg = "#45475a"
btop_selected_fg = "#89b4fa"
btop_inactive_fg = "#6c7086"
btop_graph_text = "#f5e0dc"
btop_meter_bg = "#45475a"
btop_proc_misc = "#f5e0dc"
btop_cpu_box = "#cba6f7"
btop_mem_box = "#a6e3a1"
btop_net_box = "#eba0ac"
btop_proc_box = "#89b4fa"
btop_div_line = "#6c7086"
btop_temp_start = "#a6e3a1"
btop_temp_mid = "#f9e2af"
btop_temp_end = "#f38ba8"
btop_cpu_start = "#94e2d5"
btop_cpu_mid = "#89dceb"
btop_cpu_end = "#b4befe"
btop_free_start = "#cba6f7"
btop_free_mid = "#b4befe"
btop_free_end = "#89b4fa"
btop_cached_start = "#74c7ec"
btop_cached_mid = "#89b4fa"
btop_cached_end = "#b4befe"
btop_available_start = "#fab387"
btop_available_mid = "#eba0ac"
btop_available_end = "#f38ba8"
btop_used_start = "#a6e3a1"
btop_used_mid = "#94e2d5"
btop_used_end = "#89dceb"
btop_download_start = "#fab387"
btop_download_mid = "#eba0ac"
btop_download_end = "#f38ba8"
btop_upload_start = "#a6e3a1"
btop_upload_mid = "#94e2d5"
btop_upload_end = "#89dceb"
btop_process_start = "#74c7ec"
btop_process_mid = "#b4befe"
btop_process_end = "#cba6f7"

zellij_bg = "#626880"
zellij_fg = "#c6d0f5"
zellij_black = "#292c3c"
zellij_red = "#e78284"
zellij_green = "#a6d189"
zellij_yellow = "#e5c890"
zellij_blue = "#8caaee"
zellij_magenta = "#f4b8e4"
zellij_cyan = "#99d1db"
zellij_white = "#c6d0f5"
zellij_orange = "#ef9f76"

alacritty_has_root_colors = false
alacritty_colors_primary_background = "\"#24273a\""
alacritty_colors_primary_foreground = "\"#cad3f5\""
alacritty_colors_primary_dim_foreground = "\"#8087a2\""
alacritty_colors_primary_bright_foreground = "\"#cad3f5\""
alacritty_colors_cursor_text = "\"#24273a\""
alacritty_colors_cursor_cursor = "\"#f4dbd6\""
alacritty_colors_vi_mode_cursor_text = "\"#24273a\""
alacritty_colors_vi_mode_cursor_cursor = "\"#b7bdf8\""
alacritty_colors_search_matches_foreground = "\"#24273a\""
alacritty_colors_search_matches_background = "\"#a5adcb\""
alacritty_colors_search_focused_match_foreground = "\"#24273a\""
alacritty_colors_search_focused_match_background = "\"#a6da95\""
alacritty_colors_footer_bar_foreground = "\"#24273a\""
alacritty_colors_footer_bar_background = "\"#a5adcb\""
alacritty_colors_hints_start_foreground = "\"#24273a\""
alacritty_colors_hints_start_background = "\"#eed49f\""
alacritty_colors_hints_end_foreground = "\"#24273a\""
alacritty_colors_hints_end_background = "\"#a5adcb\""
alacritty_colors_selection_text = "\"#24273a\""
alacritty_colors_selection_background = "\"#f4dbd6\""
alacritty_colors_normal_black = "\"#494d64\""
alacritty_colors_normal_red = "\"#ed8796\""
alacritty_colors_normal_green = "\"#a6da95\""
alacritty_colors_normal_yellow = "\"#eed49f\""
alacritty_colors_normal_blue = "\"#8aadf4\""
alacritty_colors_normal_magenta = "\"#f5bde6\""
alacritty_colors_normal_cyan = "\"#8bd5ca\""
alacritty_colors_normal_white = "\"#b8c0e0\""
alacritty_colors_bright_black = "\"#5b6078\""
alacritty_colors_bright_red = "\"#ed8796\""
alacritty_colors_bright_green = "\"#a6da95\""
alacritty_colors_bright_yellow = "\"#eed49f\""
alacritty_colors_bright_blue = "\"#8aadf4\""
alacritty_colors_bright_magenta = "\"#f5bde6\""
alacritty_colors_bright_cyan = "\"#8bd5ca\""
alacritty_colors_bright_white = "\"#a5adcb\""
alacritty_colors_dim_black = "\"#494d64\""
alacritty_colors_dim_red = "\"#ed8796\""
alacritty_colors_dim_green = "\"#a6da95\""
alacritty_colors_dim_yellow = "\"#eed49f\""
alacritty_colors_dim_blue = "\"#8aadf4\""
alacritty_colors_dim_magenta = "\"#f5bde6\""
alacritty_colors_dim_cyan = "\"#8bd5ca\""
alacritty_colors_dim_white = "\"#b8c0e0\""
alacritty_indexed_color_16 = "\"#f5a97f\""
alacritty_indexed_color_17 = "\"#f4dbd6\""
