format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true

palette = "ristretto"

[palettes.ristretto]
rosewater = "#e0d0c0"
pink = "#d4756e"
mauve = "#af8fd4"
lavender = "#af8fd4"
red = "#d4756e"
maroon = "#b85050"
peach = "#d49f6e"
yellow = "#d4b475"
green = "#8faf77"
teal = "#75d4b4"
sky = "#8fafd4"
sapphire = "#8fafd4"
blue = "#8fafd4"
text = "#e0d0c0"
subtext1 = "#b8a898"
subtext0 = "#908070"
overlay2 = "#605040"
overlay1 = "#483828"
overlay0 = "#382818"
surface2 = "#302018"
surface1 = "#281810"
surface0 = "#201008"
base = "#201008"
mantle = "#180c06"
crust = "#100804"
[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[package]
symbol = '󰏗 '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
