display_name = "Kanagawa"
theme_name = "kanagawa"
accent = "#7e9cd8"
foreground = "#dcd7ba"
background = "#1f1f28"
cursor = "#dcd7ba"
selection_foreground = "#c8c093"
selection_background = "#2d4f67"
color0 = "#090618"
color1 = "#c34043"
color2 = "#76946a"
color3 = "#c0a36e"
color4 = "#7e9cd8"
color5 = "#957fb8"
color6 = "#6a9589"
color7 = "#c8c093"
color8 = "#727169"
color9 = "#e82424"
color10 = "#98bb6c"
color11 = "#e6c384"
color12 = "#7fb4ca"
color13 = "#938aa9"
color14 = "#7aa89f"
color15 = "#dcd7ba"

starship_palette_name = "kanagawa"
rosewater = "#dcd7ba"
pink = "#d27e99"
mauve = "#957fb8"
red = "#c34043"
maroon = "#e82424"
peach = "#e98a3a"
yellow = "#c0a36e"
green = "#76946a"
teal = "#6a9589"
sky = "#7fb4ca"
sapphire = "#7e9cd8"
blue = "#7e9cd8"
lavender = "#9cabca"
text = "#dcd7ba"
subtext1 = "#c8c093"
subtext0 = "#727169"
overlay2 = "#54546d"
overlay1 = "#54546d"
overlay0 = "#363646"
surface2 = "#2a2a37"
surface1 = "#223249"
surface0 = "#1f1f28"
base = "#1f1f28"
mantle = "#16161d"
crust = "#16161d"

nvim_content = '''return {
	{ "rebelot/kanagawa.nvim" },
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "kanagawa",
		},
	},
}
'''

btop_main_bg = "#1f1f28"
btop_main_fg = "#dcd7ba"
btop_title = "#dcd7ba"
btop_hi_fg = "#C34043"
btop_selected_bg = "#223249"
btop_selected_fg = "#dca561"
btop_inactive_fg = "#727169"
btop_proc_misc = "#7aa89f"
btop_cpu_box = "#727169"
btop_mem_box = "#727169"
btop_net_box = "#727169"
btop_proc_box = "#727169"
btop_div_line = "#727169"
btop_temp_start = "#98BB6C"
btop_temp_mid = "#DCA561"
btop_temp_end = "#E82424"
btop_cpu_start = "#98BB6C"
btop_cpu_mid = "#DCA561"
btop_cpu_end = "#E82424"
btop_free_start = "#E82424"
btop_free_mid = "#C34043"
btop_free_end = "#FF5D62"
btop_cached_start = "#C0A36E"
btop_cached_mid = "#DCA561"
btop_cached_end = "#FF9E3B"
btop_available_start = "#938AA9"
btop_available_mid = "#957FBB"
btop_available_end = "#9CABCA"
btop_used_start = "#658594"
btop_used_mid = "#7E9CDB"
btop_used_end = "#7FB4CA"
btop_download_start = "#7E9CDB"
btop_download_mid = "#938AA9"
btop_download_end = "#957FBB"
btop_upload_start = "#DCA561"
btop_upload_mid = "#E6C384"
btop_upload_end = "#E82424"
btop_process_start = "#98BB6C"
btop_process_mid = "#DCA561"
btop_process_end = "#C34043"

zellij_bg = "#1F1F28"
zellij_fg = "#DCD7BA"
zellij_black = "#16161D"
zellij_red = "#C34043"
zellij_green = "#76946A"
zellij_yellow = "#FF9E3B"
zellij_blue = "#7E9CD8"
zellij_magenta = "#957FB8"
zellij_cyan = "#7FB4CA"
zellij_white = "#DCD7BA"
zellij_orange = "#FFA066"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "'#1f1f28'"
alacritty_colors_primary_foreground = "'#dcd7ba'"
alacritty_colors_selection_foreground = "'#c8c093'"
alacritty_colors_selection_background = "'#2d4f67'"
alacritty_colors_normal_black = "'#090618'"
alacritty_colors_normal_red = "'#c34043'"
alacritty_colors_normal_green = "'#76946a'"
alacritty_colors_normal_yellow = "'#c0a36e'"
alacritty_colors_normal_blue = "'#7e9cd8'"
alacritty_colors_normal_magenta = "'#957fb8'"
alacritty_colors_normal_cyan = "'#6a9589'"
alacritty_colors_normal_white = "'#c8c093'"
alacritty_colors_bright_black = "'#727169'"
alacritty_colors_bright_red = "'#e82424'"
alacritty_colors_bright_green = "'#98bb6c'"
alacritty_colors_bright_yellow = "'#e6c384'"
alacritty_colors_bright_blue = "'#7fb4ca'"
alacritty_colors_bright_magenta = "'#938aa9'"
alacritty_colors_bright_cyan = "'#7aa89f'"
alacritty_colors_bright_white = "'#dcd7ba'"
alacritty_indexed_color_16 = "'#ffa066'"
alacritty_indexed_color_17 = "'#ff5d62'"
