display_name = "Rose Pine"
theme_name = "rose-pine"
accent = "#c4a7e7"
foreground = "#575279"
background = "#faf4ed"
cursor = "#cecacd"
selection_foreground = "#575279"
selection_background = "#dfdad9"
color0 = "#f2e9e1"
color1 = "#b4637a"
color2 = "#286983"
color3 = "#ea9d34"
color4 = "#56949f"
color5 = "#907aa9"
color6 = "#d7827e"
color7 = "#575279"
color8 = "#9893a5"
color9 = "#b4637a"
color10 = "#286983"
color11 = "#ea9d34"
color12 = "#56949f"
color13 = "#907aa9"
color14 = "#d7827e"
color15 = "#575279"

starship_palette_name = "rose_pine"
rosewater = "#e0def4"
pink = "#eb6f92"
mauve = "#c4a7e7"
red = "#eb6f92"
maroon = "#eb6f92"
peach = "#ea9a97"
yellow = "#f6c177"
green = "#9ccfd8"
teal = "#9ccfd8"
sky = "#9ccfd8"
sapphire = "#c4a7e7"
blue = "#c4a7e7"
lavender = "#c4a7e7"
text = "#e0def4"
subtext1 = "#908caa"
subtext0 = "#6e6a86"
overlay2 = "#56527e"
overlay1 = "#44415a"
overlay0 = "#393552"
surface2 = "#26233a"
surface1 = "#1f1d30"
surface0 = "#191724"
base = "#191724"
mantle = "#1f1d2e"
crust = "#191724"

nvim_content = '''return {
	{ "rose-pine/neovim", name = "rose-pine" },
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "rose-pine-dawn",
		},
	},
}
'''

btop_main_bg = "#faf4ed"
btop_main_fg = "#575279"
btop_title = "#908caa"
btop_hi_fg = "#e0def4"
btop_selected_bg = "#524f67"
btop_selected_fg = "#f6c177"
btop_inactive_fg = "#403d52"
btop_graph_text = "#9ccfd8"
btop_meter_bg = "#9ccfd8"
btop_proc_misc = "#c4a7e7"
btop_cpu_box = "#ebbcba"
btop_mem_box = "#31748f"
btop_net_box = "#c4a7e7"
btop_proc_box = "#eb6f92"
btop_div_line = "#6e6a86"
btop_temp_start = "#ebbcba"
btop_temp_mid = "#f6c177"
btop_temp_end = "#eb6f92"
btop_cpu_start = "#f6c177"
btop_cpu_mid = "#ebbcba"
btop_cpu_end = "#eb6f92"
btop_free_start = "#eb6f92"
btop_free_mid = "#eb6f92"
btop_free_end = "#eb6f92"
btop_cached_start = "#c4a7e7"
btop_cached_mid = "#c4a7e7"
btop_cached_end = "#c4a7e7"
btop_available_start = "#31748f"
btop_available_mid = "#31748f"
btop_available_end = "#31748f"
btop_used_start = "#ebbcba"
btop_used_mid = "#ebbcba"
btop_used_end = "#ebbcba"
btop_download_start = "#31748f"
btop_download_mid = "#9ccfd8"
btop_download_end = "#9ccfd8"
btop_upload_start = "#ebbcba"
btop_upload_mid = "#eb6f92"
btop_upload_end = "#eb6f92"
btop_process_start = "#31748f"
btop_process_mid = "#9ccfd8"
btop_process_end = "#9ccfd8"

zellij_bg = "#faf4ed"
zellij_fg = "#575279"
zellij_black = "#f2e9e1"
zellij_red = "#b4637a"
zellij_green = "#286983"
zellij_yellow = "#ea9d34"
zellij_blue = "#56949f"
zellij_magenta = "#907aa9"
zellij_cyan = "#d7827e"
zellij_white = "#575279"
zellij_orange = "#fe640b"

alacritty_has_root_colors = false
alacritty_colors_primary_background = "\"#faf4ed\""
alacritty_colors_primary_foreground = "\"#575279\""
alacritty_colors_primary_dim_foreground = "\"#797593\""
alacritty_colors_primary_bright_foreground = "\"#575279\""
alacritty_colors_cursor_text = "\"#575279\""
alacritty_colors_cursor_cursor = "\"#cecacd\""
alacritty_colors_vi_mode_cursor_text = "\"#575279\""
alacritty_colors_vi_mode_cursor_cursor = "\"#cecacd\""
alacritty_colors_search_matches_foreground = "\"#797593\""
alacritty_colors_search_matches_background = "\"#f2e9e1\""
alacritty_colors_search_focused_match_foreground = "\"#faf4ed\""
alacritty_colors_search_focused_match_background = "\"#d7827e\""
alacritty_colors_footer_bar_foreground = "\"#575279\""
alacritty_colors_footer_bar_background = "\"#fffaf3\""
alacritty_colors_hints_start_foreground = "\"#797593\""
alacritty_colors_hints_start_background = "\"#fffaf3\""
alacritty_colors_hints_end_foreground = "\"#9893a5\""
alacritty_colors_hints_end_background = "\"#fffaf3\""
alacritty_colors_line_indicator_foreground = "\"None\""
alacritty_colors_line_indicator_background = "\"None\""
alacritty_colors_selection_text = "\"#575279\""
alacritty_colors_selection_background = "\"#dfdad9\""
alacritty_colors_normal_black = "\"#f2e9e1\""
alacritty_colors_normal_red = "\"#b4637a\""
alacritty_colors_normal_green = "\"#286983\""
alacritty_colors_normal_yellow = "\"#ea9d34\""
alacritty_colors_normal_blue = "\"#56949f\""
alacritty_colors_normal_magenta = "\"#907aa9\""
alacritty_colors_normal_cyan = "\"#d7827e\""
alacritty_colors_normal_white = "\"#575279\""
alacritty_colors_bright_black = "\"#9893a5\""
alacritty_colors_bright_red = "\"#b4637a\""
alacritty_colors_bright_green = "\"#286983\""
alacritty_colors_bright_yellow = "\"#ea9d34\""
alacritty_colors_bright_blue = "\"#56949f\""
alacritty_colors_bright_magenta = "\"#907aa9\""
alacritty_colors_bright_cyan = "\"#d7827e\""
alacritty_colors_bright_white = "\"#575279\""
alacritty_colors_dim_black = "\"#9893a5\""
alacritty_colors_dim_red = "\"#b4637a\""
alacritty_colors_dim_green = "\"#286983\""
alacritty_colors_dim_yellow = "\"#ea9d34\""
alacritty_colors_dim_blue = "\"#56949f\""
alacritty_colors_dim_magenta = "\"#907aa9\""
alacritty_colors_dim_cyan = "\"#d7827e\""
alacritty_colors_dim_white = "\"#575279\""
