display_name = "Matte Black"
theme_name = "matte-black"
accent = "#8fafd4"
foreground = "#bebebe"
background = "#121212"
cursor = "#eaeaea"
selection_foreground = "CellForeground"
selection_background = "#333333"
color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"

starship_palette_name = "matte_black"
rosewater = "#c8c8c8"
pink = "#d4756e"
mauve = "#af8fd4"
red = "#d4756e"
maroon = "#b45050"
peach = "#d49f6e"
yellow = "#d4b475"
green = "#8faf77"
teal = "#77c7af"
sky = "#8fafd4"
sapphire = "#8fafd4"
blue = "#8fafd4"
lavender = "#af8fd4"
text = "#c8c8c8"
subtext1 = "#a0a0a0"
subtext0 = "#787878"
overlay2 = "#585858"
overlay1 = "#404040"
overlay0 = "#303030"
surface2 = "#262626"
surface1 = "#1e1e1e"
surface0 = "#1a1a1a"
base = "#1a1a1a"
mantle = "#161616"
crust = "#131313"

nvim_content = '''return {
  { "tahayvr/matteblack.nvim", lazy = false, priority = 1000 },
  {
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "matteblack",
		},
	},
}
'''

btop_main_bg = ""
btop_main_fg = "#EAEAEA"
btop_title = "#8a8a8d"
btop_hi_fg = "#f59e0b"
btop_selected_bg = "#f59e0b"
btop_selected_fg = "#EAEAEA"
btop_inactive_fg = "#333333"
btop_proc_misc = "#8a8a8d"
btop_cpu_box = "#8a8a8d"
btop_mem_box = "#8a8a8d"
btop_net_box = "#8a8a8d"
btop_proc_box = "#8a8a8d"
btop_div_line = "#8a8a8d"
btop_temp_start = "#8a8a8d"
btop_temp_mid = "#f59e0b"
btop_temp_end = "#b91c1c"
btop_cpu_start = "#8a8a8d"
btop_cpu_mid = "#f59e0b"
btop_cpu_end = "#b91c1c"
btop_free_start = "#8a8a8d"
btop_free_mid = "#f59e0b"
btop_free_end = "#b91c1c"
btop_cached_start = "#8a8a8d"
btop_cached_mid = "#f59e0b"
btop_cached_end = "#b91c1c"
btop_available_start = "#8a8a8d"
btop_available_mid = "#f59e0b"
btop_available_end = "#b91c1c"
btop_used_start = "#8a8a8d"
btop_used_mid = "#f59e0b"
btop_used_end = "#b91c1c"
btop_download_start = "#8a8a8d"
btop_download_mid = "#f59e0b"
btop_download_end = "#b91c1c"
btop_upload_start = "#8a8a8d"
btop_upload_mid = "#f59e0b"
btop_upload_end = "#b91c1c"

zellij_bg = "#121212"
zellij_fg = "#bebebe"
zellij_black = "#333333"
zellij_red = "#D35F5F"
zellij_green = "#FFC107"
zellij_yellow = "#b91c1c"
zellij_blue = "#e68e0d"
zellij_magenta = "#D35F5F"
zellij_cyan = "#bebebe"
zellij_white = "#bebebe"
zellij_orange = "#FFA066"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "\"#121212\""
alacritty_colors_primary_foreground = "\"#bebebe\""
alacritty_colors_primary_dim_foreground = "\"#8a8a8d\""
alacritty_colors_cursor_text = "\"#121212\""
alacritty_colors_cursor_cursor = "\"#eaeaea\""
alacritty_colors_vi_mode_cursor_text = "\"#121212\""
alacritty_colors_vi_mode_cursor_cursor = "\"#eaeaea\""
alacritty_colors_selection_text = "\"CellForeground\""
alacritty_colors_selection_background = "\"#333333\""
alacritty_colors_normal_black = "\"#333333\""
alacritty_colors_normal_red = "\"#D35F5F\""
alacritty_colors_normal_green = "\"#FFC107\""
alacritty_colors_normal_yellow = "\"#b91c1c\""
alacritty_colors_normal_blue = "\"#e68e0d\""
alacritty_colors_normal_magenta = "\"#D35F5F\""
alacritty_colors_normal_cyan = "\"#bebebe\""
alacritty_colors_normal_white = "\"#bebebe\""
alacritty_colors_bright_black = "\"#8a8a8d\""
alacritty_colors_bright_red = "\"#B91C1C\""
alacritty_colors_bright_green = "\"#FFC107\""
alacritty_colors_bright_yellow = "\"#b90a0a\""
alacritty_colors_bright_blue = "\"#f59e0b\""
alacritty_colors_bright_magenta = "\"#B91C1C\""
alacritty_colors_bright_cyan = "\"#eaeaea\""
alacritty_colors_bright_white = "\"#ffffff\""
alacritty_font_size = "12.0"
