display_name = "Nord"
theme_name = "nord"
accent = "#81a1c1"
foreground = "#d8dee9"
background = "#2e3440"
cursor = "#d8dee9"
selection_foreground = "CellForeground"
selection_background = "#4c566a"
color0 = "#3b4252"
color1 = "#bf616a"
color2 = "#a3be8c"
color3 = "#ebcb8b"
color4 = "#81a1c1"
color5 = "#b48ead"
color6 = "#88c0d0"
color7 = "#e5e9f0"
color8 = "#4c566a"
color9 = "#bf616a"
color10 = "#a3be8c"
color11 = "#ebcb8b"
color12 = "#81a1c1"
color13 = "#b48ead"
color14 = "#8fbcbb"
color15 = "#eceff4"

starship_palette_name = "nord"
rosewater = "#eceff4"
pink = "#b48ead"
mauve = "#b48ead"
red = "#bf616a"
maroon = "#bf616a"
peach = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
teal = "#8fbcbb"
sky = "#88c0d0"
sapphire = "#81a1c1"
blue = "#81a1c1"
lavender = "#b48ead"
text = "#eceff4"
subtext1 = "#d8dee9"
subtext0 = "#81a1c1"
overlay2 = "#616e88"
overlay1 = "#4c566a"
overlay0 = "#434c5e"
surface2 = "#3b4252"
surface1 = "#2e3440"
surface0 = "#2e3440"
base = "#2e3440"
mantle = "#2e3440"
crust = "#2e3440"

nvim_content = '''return {
	{ "EdenEast/nightfox.nvim" },
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "nordfox",
		},
	},
}
'''

btop_main_bg = "#2E3440"
btop_main_fg = "#D8DEE9"
btop_title = "#8FBCBB"
btop_hi_fg = "#5E81AC"
btop_selected_bg = "#4C566A"
btop_selected_fg = "#ECEFF4"
btop_inactive_fg = "#4C566A"
btop_proc_misc = "#5E81AC"
btop_cpu_box = "#4C566A"
btop_mem_box = "#4C566A"
btop_net_box = "#4C566A"
btop_proc_box = "#4C566A"
btop_div_line = "#4C566A"
btop_temp_start = "#81A1C1"
btop_temp_mid = "#88C0D0"
btop_temp_end = "#ECEFF4"
btop_cpu_start = "#81A1C1"
btop_cpu_mid = "#88C0D0"
btop_cpu_end = "#ECEFF4"
btop_free_start = "#81A1C1"
btop_free_mid = "#88C0D0"
btop_free_end = "#ECEFF4"
btop_cached_start = "#81A1C1"
btop_cached_mid = "#88C0D0"
btop_cached_end = "#ECEFF4"
btop_available_start = "#81A1C1"
btop_available_mid = "#88C0D0"
btop_available_end = "#ECEFF4"
btop_used_start = "#81A1C1"
btop_used_mid = "#88C0D0"
btop_used_end = "#ECEFF4"
btop_download_start = "#81A1C1"
btop_download_mid = "#88C0D0"
btop_download_end = "#ECEFF4"
btop_upload_start = "#81A1C1"
btop_upload_mid = "#88C0D0"
btop_upload_end = "#ECEFF4"

zellij_bg = "#2E3440"
zellij_fg = "#D8DEE9"
zellij_black = "#3B4252"
zellij_red = "#BF616A"
zellij_green = "#A3BE8C"
zellij_yellow = "#EBCB8B"
zellij_blue = "#81A1C1"
zellij_magenta = "#B48EAD"
zellij_cyan = "#88C0D0"
zellij_white = "#E5E9F0"
zellij_orange = "#D08770"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "\"#2e3440\""
alacritty_colors_primary_foreground = "\"#d8dee9\""
alacritty_colors_primary_dim_foreground = "\"#a5abb6\""
alacritty_colors_cursor_text = "\"#2e3440\""
alacritty_colors_cursor_cursor = "\"#d8dee9\""
alacritty_colors_vi_mode_cursor_text = "\"#2e3440\""
alacritty_colors_vi_mode_cursor_cursor = "\"#d8dee9\""
alacritty_colors_selection_text = "\"CellForeground\""
alacritty_colors_selection_background = "\"#4c566a\""
alacritty_colors_normal_black = "\"#3b4252\""
alacritty_colors_normal_red = "\"#bf616a\""
alacritty_colors_normal_green = "\"#a3be8c\""
alacritty_colors_normal_yellow = "\"#ebcb8b\""
alacritty_colors_normal_blue = "\"#81a1c1\""
alacritty_colors_normal_magenta = "\"#b48ead\""
alacritty_colors_normal_cyan = "\"#88c0d0\""
alacritty_colors_normal_white = "\"#e5e9f0\""
alacritty_colors_bright_black = "\"#4c566a\""
alacritty_colors_bright_red = "\"#bf616a\""
alacritty_colors_bright_green = "\"#a3be8c\""
alacritty_colors_bright_yellow = "\"#ebcb8b\""
alacritty_colors_bright_blue = "\"#81a1c1\""
alacritty_colors_bright_magenta = "\"#b48ead\""
alacritty_colors_bright_cyan = "\"#8fbcbb\""
alacritty_colors_bright_white = "\"#eceff4\""
alacritty_colors_dim_black = "\"#373e4d\""
alacritty_colors_dim_red = "\"#94545d\""
alacritty_colors_dim_green = "\"#809575\""
alacritty_colors_dim_yellow = "\"#b29e75\""
alacritty_colors_dim_blue = "\"#68809a\""
alacritty_colors_dim_magenta = "\"#8c738c\""
alacritty_colors_dim_cyan = "\"#6d96a5\""
alacritty_colors_dim_white = "\"#aeb3bb\""
