display_name = "Everforest"
theme_name = "everforest"
accent = "#7fbbb3"
foreground = "#d3c6aa"
background = "#2d353b"
cursor = "#d3c6aa"
selection_foreground = "#2d353b"
selection_background = "#374145"
color0 = "#475258"
color1 = "#e67e80"
color2 = "#a7c080"
color3 = "#dbbc7f"
color4 = "#7fbbb3"
color5 = "#d699b6"
color6 = "#83c092"
color7 = "#d3c6aa"
color8 = "#475258"
color9 = "#e67e80"
color10 = "#a7c080"
color11 = "#dbbc7f"
color12 = "#7fbbb3"
color13 = "#d699b6"
color14 = "#83c092"
color15 = "#d3c6aa"

starship_palette_name = "everforest"
rosewater = "#d3c6aa"
pink = "#d699b6"
mauve = "#d699b6"
red = "#e67e80"
maroon = "#e67e80"
peach = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
teal = "#83c092"
sky = "#7fbbb3"
sapphire = "#7fbbb3"
blue = "#7fbbb3"
lavender = "#d699b6"
text = "#d3c6aa"
subtext1 = "#a7c080"
subtext0 = "#9da9a0"
overlay2 = "#859289"
overlay1 = "#5c6a72"
overlay0 = "#4b565c"
surface2 = "#374145"
surface1 = "#2d353b"
surface0 = "#272e33"
base = "#272e33"
mantle = "#1e2326"
crust = "#1e2326"

nvim_content = '''return {
	{ "neanias/everforest-nvim" },
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "everforest",
			background = "soft",
		},
	},
}
'''

btop_main_bg = "#2d353b"
btop_main_fg = "#d3c6aa"
btop_title = "#d3c6aa"
btop_hi_fg = "#e67e80"
btop_selected_bg = "#3d484d"
btop_selected_fg = "#dbbc7f"
btop_inactive_fg = "#2d353b"
btop_graph_text = "#d3c6aa"
btop_proc_misc = "#a7c080"
btop_cpu_box = "#3d484d"
btop_mem_box = "#3d484d"
btop_net_box = "#3d484d"
btop_proc_box = "#3d484d"
btop_div_line = "#3d484d"
btop_temp_start = "#a7c080"
btop_temp_mid = "#dbbc7f"
btop_temp_end = "#f85552"
btop_cpu_start = "#a7c080"
btop_cpu_mid = "#dbbc7f"
btop_cpu_end = "#f85552"
btop_free_start = "#f85552"
btop_free_mid = "#dbbc7f"
btop_free_end = "#a7c080"
btop_cached_start = "#7fbbb3"
btop_cached_mid = "#83c092"
btop_cached_end = "#a7c080"
btop_available_start = "#f85552"
btop_available_mid = "#dbbc7f"
btop_available_end = "#a7c080"
btop_used_start = "#a7c080"
btop_used_mid = "#dbbc7f"
btop_used_end = "#f85552"
btop_download_start = "#a7c080"
btop_download_mid = "#83c092"
btop_download_end = "#7fbbb3"
btop_upload_start = "#dbbc7f"
btop_upload_mid = "#e69875"
btop_upload_end = "#e67e80"
btop_process_start = "#a7c080"
btop_process_mid = "#e67e80"
btop_process_end = "#f85552"

zellij_bg = "#2b3339"
zellij_fg = "#d3c6aa"
zellij_black = "#4b565c"
zellij_red = "#e67e80"
zellij_green = "#a7c080"
zellij_yellow = "#dbbc7f"
zellij_blue = "#7fbbb3"
zellij_magenta = "#d699b6"
zellij_cyan = "#83c092"
zellij_white = "#d3c6aa"
zellij_orange = "#FF9E64"

alacritty_has_root_colors = true
alacritty_colors_primary_background = "'#2d353b'"
alacritty_colors_primary_foreground = "'#d3c6aa'"
alacritty_colors_selection_background = "'#374145'"
alacritty_colors_normal_black = "'#475258'"
alacritty_colors_normal_red = "'#e67e80'"
alacritty_colors_normal_green = "'#a7c080'"
alacritty_colors_normal_yellow = "'#dbbc7f'"
alacritty_colors_normal_blue = "'#7fbbb3'"
alacritty_colors_normal_magenta = "'#d699b6'"
alacritty_colors_normal_cyan = "'#83c092'"
alacritty_colors_normal_white = "'#d3c6aa'"
alacritty_colors_bright_black = "'#475258'"
alacritty_colors_bright_red = "'#e67e80'"
alacritty_colors_bright_green = "'#a7c080'"
alacritty_colors_bright_yellow = "'#dbbc7f'"
alacritty_colors_bright_blue = "'#7fbbb3'"
alacritty_colors_bright_magenta = "'#d699b6'"
alacritty_colors_bright_cyan = "'#83c092'"
alacritty_colors_bright_white = "'#d3c6aa'"
