format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true

palette = "everforest"

[palettes.everforest]
rosewater = "#d3c6aa"
pink = "#d699b6"
mauve = "#d699b6"
lavender = "#d699b6"
red = "#e67e80"
maroon = "#e67e80"
peach = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
teal = "#83c092"
sky = "#7fbbb3"
sapphire = "#7fbbb3"
blue = "#7fbbb3"
text = "#d3c6aa"
subtext1 = "#a7c080"
subtext0 = "#9da9a0"
overlay2 = "#859289"
overlay1 = "#5c6a72"
overlay0 = "#4b565c"
surface2 = "#374145"
surface1 = "#2d353b"
surface0 = "#272e33"
base = "#272e33"
mantle = "#1e2326"
crust = "#1e2326"
[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[package]
symbol = ' '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
